/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#fbbf24',
        'on-primary-container': '#6c4f00',
        'secondary-container': '#ec6a06',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-bright': '#3a3939',
        'surface-dim': '#131313',
        'surface': '#131313',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d3c5ac',
        'outline': '#9c8f79',
        'outline-variant': '#4f4633',
        'primary': '#ffe1a7',
        'primary-fixed': '#ffdf9f',
        'primary-fixed-dim': '#f9bd22',
        'on-primary': '#402d00',
        'on-primary-fixed': '#261a00',
        'secondary': '#ffb690',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb690',
        'on-secondary': '#552100',
        'on-secondary-container': '#4a1c00',
        'on-secondary-fixed': '#341100',
        'on-secondary-fixed-variant': '#783200',
        'tertiary': '#f0e5ba',
        'tertiary-container': '#d3c99f',
        'tertiary-fixed': '#ede3b8',
        'tertiary-fixed-dim': '#d1c79d',
        'on-tertiary': '#363113',
        'on-tertiary-container': '#5b5433',
        'on-tertiary-fixed': '#201c02',
        'on-tertiary-fixed-variant': '#4d4727',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#795900',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0px',
        'lg': '0px',
        'xl': '0px',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
